"""first msg

Revision ID: 02f9fbe9e57c
Revises: 56e41e35fe76
Create Date: 2023-06-17 19:05:27.602828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02f9fbe9e57c'
down_revision = '56e41e35fe76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('about_event',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('about_event',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
